const GEN_NOTE = '<!-- Generated by scripts/validate-scenarios.sh — do not edit by hand. -->';
export const CATALOG_BEGIN = '<!-- BEGIN SCENARIO CATALOG -->';
export const CATALOG_END = '<!-- END SCENARIO CATALOG -->';

const DIFFICULTY_RANK = new Map([
  ['beginner', 0],
  ['intermediate', 1],
  ['advanced', 2],
]);

function difficultyRank(difficulty) {
  return DIFFICULTY_RANK.get(difficulty) ?? Number.MAX_SAFE_INTEGER;
}

function sortCatalogScenarios(scenarios) {
  return scenarios.slice().sort((a, b) => {
    const ad = difficultyRank(a.manifest.difficulty);
    const bd = difficultyRank(b.manifest.difficulty);
    if (ad !== bd) return ad - bd;
    const at = a.manifest.title ?? a.id;
    const bt = b.manifest.title ?? b.id;
    const titleDiff = at.localeCompare(bt);
    if (titleDiff !== 0) return titleDiff;
    return a.id.localeCompare(b.id);
  });
}

function renderRow(scenario) {
  const { id, manifest } = scenario;
  const title = manifest.title ?? id;
  const minutes = manifest.estimatedMinutes ? `${manifest.estimatedMinutes}m` : '—';
  const difficulty = manifest.difficulty ?? '—';
  const cost = manifest.costProfile ?? '—';
  return `| [${title}](scenarios/${id}/) | ${manifest.platform} | ${manifest.incidentType} | ${manifest.severity} | ${minutes} | ${difficulty} | ${cost} | ${manifest.summary} |`;
}

export function renderCatalog(scenarios) {
  return [
    CATALOG_BEGIN,
    GEN_NOTE,
    '',
    '| Scenario | Platform | Incident | Severity | Est. | Difficulty | Cost | Summary |',
    '| --- | --- | --- | --- | --- | --- | --- | --- |',
    ...sortCatalogScenarios(scenarios).map(renderRow),
    '',
    CATALOG_END,
  ].join('\n');
}
