import { test } from 'node:test';
import assert from 'node:assert/strict';
import { renderCatalog, CATALOG_BEGIN, CATALOG_END } from '../lib/generate.js';

const scenarios = [
  {
    id: 'zeta-disk',
    manifest: {
      title: 'Zeta Disk',
      platform: 'Azure VM',
      incidentType: 'disk saturation',
      severity: 2,
      estimatedMinutes: 15,
      difficulty: 'beginner',
      costProfile: 'low',
      summary: 'Disk usage is climbing on a VM.',
    },
  },
  {
    id: 'alpha-deploy',
    manifest: {
      title: 'Alpha Deploy',
      platform: 'Azure App Service',
      incidentType: 'deployment failure',
      severity: 3,
      estimatedMinutes: 20,
      difficulty: 'beginner',
      costProfile: 'medium',
      summary: 'A deployment stops the site from serving traffic.',
    },
  },
  {
    id: 'beta-cpu',
    manifest: {
      title: 'Beta CPU',
      platform: 'AKS',
      incidentType: 'cpu runaway',
      severity: 4,
      estimatedMinutes: 25,
      difficulty: 'intermediate',
      costProfile: 'high',
      summary: 'Pods are consuming too much CPU.',
    },
  },
  {
    id: 'gamma-auth',
    manifest: {
      title: 'Gamma Auth',
      platform: 'AKS',
      incidentType: 'identity regression',
      severity: 4,
      estimatedMinutes: 30,
      difficulty: 'advanced',
      costProfile: 'high',
      summary: 'A workload identity change blocks access.',
    },
  },
];

test('renderCatalog emits the root catalog block with markers, columns, links, and sorted rows', () => {
  const md = renderCatalog(scenarios);

  assert.ok(md.startsWith(CATALOG_BEGIN));
  assert.ok(md.trimEnd().endsWith(CATALOG_END));
  assert.match(md, /Generated by scripts\/validate-scenarios\.sh — do not edit by hand\./);
  assert.match(md, /\| Scenario \| Platform \| Incident \| Severity \| Est\. \| Difficulty \| Cost \| Summary \|/);
  assert.match(md, /\[Alpha Deploy\]\(scenarios\/alpha-deploy\/\)/);
  assert.match(md, /\[Zeta Disk\]\(scenarios\/zeta-disk\/\)/);

  assert.ok(md.indexOf('[Alpha Deploy](scenarios/alpha-deploy/)') < md.indexOf('[Zeta Disk](scenarios/zeta-disk/)'));
  assert.ok(md.indexOf('[Zeta Disk](scenarios/zeta-disk/)') < md.indexOf('[Beta CPU](scenarios/beta-cpu/)'));
  assert.ok(md.indexOf('[Beta CPU](scenarios/beta-cpu/)') < md.indexOf('[Gamma Auth](scenarios/gamma-auth/)'));
});
