// GENERATED by scripts/scenario-tools — do not edit by hand.
// Aggregates per-scenario alert modules for the appservice track.

@description('Azure region for alert resources')
param location string

@description('Base workload name for resource naming')
param workloadName string

@description('Resource tags')
param tags object

@description('Scope resource ID each scenario alert binds to')
param logAnalyticsResourceId string

module cloudAgentHandoverAlert '../../../scenarios/cloud-agent-handover/alert.bicep' = {
  name: 'alert-cloud-agent-handover'
  params: {
    location: location
    workloadName: workloadName
    tags: tags
    scopeResourceId: logAnalyticsResourceId
  }
}
